# Tâche 1 — Algorithme classique de découverte de PFDs

**Cours :** Data Wrangling — *Pattern-Based Dependencies and Agentic Discovery for Data Quality* (K. Belhajjame)

Ce notebook présente, étape par étape, l'algorithme classique de découverte de **Pattern Functional Dependencies (PFDs) approximatives**.

## Rappel théorique

Une **PFD** est une règle de la forme :

> Si la valeur de la colonne `X` correspond au pattern `P₁`,
> alors la valeur de la colonne `Y` doit correspondre au pattern `P₂`.

La version **approximative** tolère un taux d'exception `ε` :

$$\text{confiance}(X \to Y) = \frac{|\{t : t \models P_1 \land t \models P_2\}|}{|\{t : t \models P_1\}|}$$

$$\text{PFD valide} \Leftrightarrow \text{confiance} \geq (1 - \varepsilon)$$

## Plan du notebook

Le pipeline de découverte classique comporte 4 étapes (cf. slides 8-15 du cours) :

| Étape | Module Python                  | Rôle                                      |
|-------|--------------------------------|-------------------------------------------|
| 1     | `src/pattern_extractor.py`     | Extraction de patterns (préfixes, tokens) |
| 2     | `src/candidate_generator.py`   | Génération de candidats (X → Y)           |
| 3     | `pfd_verifier.py`              | Validation (support + confiance)          |
| 4     | `src/rule_generalizer.py`      | Généralisation des règles                 |

Le tout est orchestré par `pfd_discovery.py::discover()`.

---
## Configuration & imports

In [1]:
# Ajouter la racine du projet au sys.path (le notebook est dans notebooks/)
import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), "..")))

import pandas as pd
pd.set_option("display.max_colwidth", 60)
pd.set_option("display.max_rows", 12)

# Modules de l'algorithme classique
from src.pattern_extractor   import (
    extract_prefixes, extract_tokens, extract_ngrams,
    prefix_patterns, token_patterns, extract_all_patterns,
)
from src.candidate_generator import generate_candidates, generate_all_candidates
from src.rule_generalizer    import generalize_rules, _longest_common_prefix
from pfd_verifier            import verifier_pfd, rapport_pfd
from pfd_discovery           import discover, print_results

print("Imports OK")

Imports OK

### Chargement des datasets

On utilise les 3 fichiers du sous-dossier `data/pfd_validation/` :

- **t1.csv** : 9 101 employés du comté de Montgomery (Maryland).
- **t2.csv** : 3 502 employeurs de Chicago.
- **t3.csv** : 1 077 licences d'alcool du Maryland.

In [2]:
DATA = "../data/pfd_validation"

t1 = pd.read_csv(f"{DATA}/t1.csv")
t2 = pd.read_csv(f"{DATA}/t2.csv")
t3 = pd.read_csv(f"{DATA}/t3.csv")

print(f"t1 : {t1.shape[0]:>5} lignes × {t1.shape[1]} colonnes  — {list(t1.columns)[:4]}...")
print(f"t2 : {t2.shape[0]:>5} lignes × {t2.shape[1]} colonnes  — {list(t2.columns)[:4]}...")
print(f"t3 : {t3.shape[0]:>5} lignes × {t3.shape[1]} colonnes  — {list(t3.columns)[:4]}...")

t1 :  9101 lignes × 9 colonnes  — ['Full Name', 'Gender', 'Department', 'Department Name']...
t2 :  3502 lignes × 13 colonnes  — ['Year', 'EMPLOYER_ID', 'NAME', 'ADDRESS_1']...
t3 :  1077 lignes × 9 colonnes  — ['Licensee Name', 'Street', 'City', 'State']...

In [3]:
# Aperçu de t2 (employeurs de Chicago)
t2[["NAME", "CITY", "STATE", "ZIP", "PHONE"]].head()

                  NAME     CITY STATE    ZIP         PHONE
0     Lighten-Gale LLC  Chicago    Il  60603  312-920-1500
1   Nicolay & Dart LLC  Chicago    IL  60602  312-701-0221
2   Nicolay & Dart LLC  Chicago    IL  60602  312-701-0221
3          Carol Ronen  Chicago    IL  60660  773-919-4240
4  Thompson Coburn LLP  Chicago    IL  60603  312-580-2228

---
## Étape 1 — Extraction de patterns

> *« Each value generates many candidate patterns. Use frequency thresholds. »*
> — slide 10

L'idée : transformer les valeurs brutes en **patterns candidats** (préfixes, tokens, n-grams) qui pourront servir d'antécédent (`X`) dans une PFD.

### 1.a — Sur une valeur unique

In [4]:
# Préfixes — exemple emprunté au cours (slide 17)
print("extract_prefixes('90012', k_max=3) =", extract_prefixes("90012", k_max=3))
print("extract_prefixes('John Smith', k_max=4) =", extract_prefixes("John Smith", k_max=4))

# Premier token (slide 17 : first_token(name) = 'John')
print("extract_tokens('John Smith') =", extract_tokens("John Smith"))
print("extract_tokens('Los Angeles, CA') =", extract_tokens("Los Angeles, CA"))

# N-grams (slide 10)
print("extract_ngrams('90012', 3) =", extract_ngrams("90012", 3))

extract_prefixes('90012', k_max=3) = ['9', '90', '900']
extract_prefixes('John Smith', k_max=4) = ['J', 'Jo', 'Joh', 'John']
extract_tokens('John Smith') = ['John', 'Smith']
extract_tokens('Los Angeles, CA') = ['Los', 'Angeles', 'CA']
extract_ngrams('90012', 3) = ['900', '001', '012']

### 1.b — Sur une colonne entière

`prefix_patterns()` renvoie un dictionnaire `{pattern: [indices_des_lignes]}` filtré par support minimum.

Sur la colonne **ZIP** de Chicago, on s'attend à trouver le préfixe `606` (signature des ZIP du centre-ville).

In [5]:
# Préfixes de longueur 1 à 3 sur ZIP de t2.csv
zip_prefixes = prefix_patterns(t2["ZIP"], k_max=3, min_support=30)

# Top 10 préfixes par support (nombre de lignes)
top = sorted(zip_prefixes.items(), key=lambda kv: -len(kv[1]))[:10]
print(f"  Pattern  | Support")
print(f"  ─────────┼────────")
for pat, idx in top:
    print(f"  {pat:>7}  |  {len(idx):>5}")

  Pattern  | Support
  ─────────┼────────
        6  |   2509
       60  |   2456
      606  |   2131
        1  |    354
       10  |    285
      100  |    242
        2  |    136
      600  |     97
        0  |     96
        4  |     88

On observe bien que **`606` couvre ~2 100 lignes**, soit la grande majorité des employeurs de Chicago — c'est notre futur antécédent.

In [6]:
# Tokens — sur les noms d'employeurs
name_tokens = token_patterns(t2["NAME"], min_support=20)
top_names = sorted(name_tokens.items(), key=lambda kv: -len(kv[1]))[:8]
print(f"  Premier mot  | Support")
print(f"  ─────────────┼────────")
for tok, idx in top_names:
    print(f"  {tok:>11}  |  {len(idx):>5}")

  Premier mot  | Support
  ─────────────┼────────
     Illinois  |     64
       Morgan  |     53
      Chicago  |     51
         SEIU  |     45
          The  |     43
      William  |     40
         Neal  |     37
          DLA  |     33

### 1.c — Tous les patterns d'une colonne en une fois

`extract_all_patterns()` est le point d'entrée unifié appelé par le pipeline.

In [7]:
# Synthèse pour la colonne ZIP
zip_all = extract_all_patterns(t2["ZIP"], k_max=3, min_support=30)
for match_type, pmap in zip_all.items():
    print(f"  {match_type:<12}  →  {len(pmap)} patterns retenus")

  startswith    →  30 patterns retenus
  first_token   →  19 patterns retenus

---
## Étape 2 — Génération de candidats

> *« Generate candidate dependencies of the form X → Y. »* — slide 13

Pour chaque pattern `P_X` retenu et chaque colonne cible `Y` :

1. On isole les lignes où `col_X` matche `P_X`.
2. On cherche la **valeur la plus fréquente** de `col_Y` dans ce sous-ensemble (mode).
3. Cette valeur devient le `pattern_Y` candidat — la règle à tester est :
   « `col_X` matche `P_X` ⇒ `col_Y` = `top_Y` ».

In [8]:
# Générer les candidats pour ZIP → toutes les autres colonnes
zip_candidates = generate_candidates(
    df=t2,
    col_X="ZIP",
    pattern_map=zip_prefixes,
    match_type="startswith",
    target_cols=list(t2.columns),
    min_support=30,
)

print(f"Nombre de candidats générés : {len(zip_candidates)}")
print("\n5 candidats avec la confiance brute la plus élevée :\n")
top_cand = sorted(zip_candidates, key=lambda c: -c["raw_confidence"])[:5]
for c in top_cand:
    print(f"  ZIP sw '{c['pattern_X']}' → {c['col_Y']} = {c['pattern_Y']!r}   "
          f"(support={c['support']}, conf_brute={c['raw_confidence']:.1%})")

Nombre de candidats générés : 357

5 candidats avec la confiance brute la plus élevée :

  ZIP sw '6' → COUNTRY = 'United States'   (support=2509, conf_brute=100.0%)
  ZIP sw '60' → COUNTRY = 'United States'   (support=2456, conf_brute=100.0%)
  ZIP sw '606' → COUNTRY = 'United States'   (support=2131, conf_brute=100.0%)
  ZIP sw '601' → STATE = 'IL'   (support=81, conf_brute=100.0%)
  ZIP sw '601' → COUNTRY = 'United States'   (support=81, conf_brute=100.0%)

La **confiance brute** affichée ici n'est qu'une approximation : la validation finale (étape 3) recalcule la confiance exacte via `pfd_verifier`. Pour la plupart des cas elles coïncident — elles ne diffèrent qu'en présence de NaN dans `col_Y`.

In [9]:
# Le pipeline complet appellera generate_all_candidates qui itère sur toutes
# les colonnes sources et tous les types de patterns
pattern_maps = {}
for col in ["ZIP", "PHONE", "CITY"]:
    pmap = extract_all_patterns(t2[col], k_max=3, min_support=30)
    if pmap:
        pattern_maps[col] = pmap

all_cands = generate_all_candidates(t2, pattern_maps, target_cols=list(t2.columns), min_support=30)
print(f"Candidats pour 3 colonnes sources (ZIP, PHONE, CITY) : {len(all_cands)}")

Candidats pour 3 colonnes sources (ZIP, PHONE, CITY) : 1483

---
## Étape 3 — Validation

> *« Determine whether a candidate X → Y is a valid (approximate) PFD. »*
> — slide 14

On utilise `pfd_verifier.verifier_pfd()` qui applique les formules **support / confidence / noise** des slides 7-8.

Pour notre candidat phare *« ZIP sw `606` → CITY = `Chicago` »* avec `ε = 0.1` :

In [10]:
res = verifier_pfd(
    t2,
    col_X="ZIP",   pattern_X="606",
    col_Y="CITY",  pattern_Y="Chicago",
    epsilon=0.1,
    match_type_X="startswith",
    match_type_Y="exact",
)

print(f"  Lignes où ZIP commence par '606' : {res['n_matching_X']:>5,}")
print(f"  Lignes où CITY = 'Chicago' dans ce groupe : {res['n_valid']:>5,}")
print(f"  Violations : {res['n_violations']:>5,}")
print(f"  Confiance : {res['confidence']:.2%}  (seuil = {1-0.1:.0%})")
print(f"  is_valid : {res['is_valid']}")

print("\n  Exemples de violations :")
for v in res['examples_violations']:
    print(f"    ZIP={v['ZIP']!r} | CITY={v['CITY']!r}")

  Lignes où ZIP commence par '606' : 2,131
  Lignes où CITY = 'Chicago' dans ce groupe : 2,094
  Violations :    37
  Confiance : 98.26%  (seuil = 90%)
  is_valid : True

  Exemples de violations :
    ZIP='60622' | CITY='chicago'
    ZIP='60602' | CITY='chicago'
    ZIP='60602' | CITY='chicago'

**Découverte intéressante** : les 37 violations sont **toutes** dues à `'chicago'` en minuscules. C'est un **problème de qualité de données** révélé par la PFD — exactement le cas d'usage défendu par le cours (slide 4 : *« PFDs can detect errors that FDs cannot »*).

### Validation de tous les candidats

In [11]:
# Pour chaque candidat, on appelle verifier_pfd et on garde les valides
valid_pfds = []
for cand in all_cands:
    r = verifier_pfd(
        t2,
        col_X=cand["col_X"], pattern_X=cand["pattern_X"],
        col_Y=cand["col_Y"], pattern_Y=cand["pattern_Y"],
        epsilon=0.1,
        match_type_X=cand["match_type_X"],
        match_type_Y=cand["match_type_Y"],
    )
    if r["is_valid"]:
        cand.update({"confidence": r["confidence"],
                     "n_matching_X": r["n_matching_X"],
                     "n_violations": r["n_violations"]})
        valid_pfds.append(cand)

print(f"  PFDs valides : {len(valid_pfds)} / {len(all_cands)} candidats")

  PFDs valides : 369 / 1483 candidats

---
## Étape 4 — Généralisation

> *« Merge specific patterns into more general and meaningful rules. »*
> — slide 15

L'exemple canonique du cours :

> `"John*" → M` + `"James*" → M` → `first_token(name) → M`

Notre implémentation a deux mécanismes :

1. **Fusion par plus grand préfixe commun** (`fuse_rules`) — si plusieurs règles partagent `(col_X, col_Y, val_Y)`, on essaie de les remplacer par une règle avec le préfixe commun, sous réserve que la confiance reste au-dessus du seuil.
2. **Élagage des règles dominées** (`prune_dominated`) — si `"6"` et `"606"` mènent toutes deux à `"Chicago"`, on garde seulement la plus générale (`"6"`).

In [12]:
# Démonstration du préfixe commun
print("Préfixe commun de ['BBW1', 'BBW2', 'BBWLHR']  =", repr(_longest_common_prefix(['BBW1', 'BBW2', 'BBWLHR'])))
print("Préfixe commun de ['John', 'Joel', 'Joseph']   =", repr(_longest_common_prefix(['John', 'Joel', 'Joseph'])))
print("Préfixe commun de ['606', '770']               =", repr(_longest_common_prefix(['606', '770'])))

Préfixe commun de ['BBW1', 'BBW2', 'BBWLHR']  = 'BBW'
Préfixe commun de ['John', 'Joel', 'Joseph']   = 'Jo'
Préfixe commun de ['606', '770']               = ''

In [13]:
# Application sur nos PFDs valides
generalized = generalize_rules(valid_pfds, t2, epsilon=0.1)
print(f"  Avant généralisation : {len(valid_pfds)} règles")
print(f"  Après généralisation : {len(generalized)} règles")
print(f"  Réduction            : {(1 - len(generalized)/len(valid_pfds)):.0%}")

n_fused = sum(1 for r in generalized if r.get("generalized_from", 0) > 1)
print(f"  Dont {n_fused} règles fusionnées depuis plusieurs règles spécifiques")

  Avant généralisation : 369 règles
  Après généralisation : 109 règles
  Réduction            : 70%
  Dont 17 règles fusionnées depuis plusieurs règles spécifiques

---
## Le pipeline complet — `discover()`

La fonction `discover()` orchestre les 4 étapes ci-dessus. Elle est exposée
via la CLI `python pfd_discovery.py --dataset ...` mais on peut aussi
l'appeler directement.

### Pipeline sur t2.csv (employeurs Chicago)

In [14]:
pfds_t2 = discover(t2, epsilon=0.1, min_support=30, k_max=3, verbose=True)
print_results(pfds_t2, top_n=10)

[1/4] Extraction des patterns  (k_max=3, min_support=30)...
    13 colonnes analysées, 493 patterns extraits

[2/4] Génération des candidats PFDs...

    5,061 candidats générés

[3/4] Validation (epsilon=0.1)...

    1087 PFDs valides (sur 5,061 candidats testés)

[4/4] Généralisation des règles...
    324 règles conservées (27 généralisées, 763 élagées/fusionnées)

  Temps total : 10.80s

========================================================================
  #    Règle PFD                                      Conf   Support    Viol
========================================================================
  1    ZIP [startswith:'6'] -> COUNTRY = 'Unite...  100.0%     2,509       0
  2    PHONE [startswith:'3'] -> COUNTRY = 'Uni...  100.0%     1,978       0
  3    EMPLOYER_ID [startswith:'4'] -> COUNTRY ...  100.0%     1,876       0
  4    FAX [startswith:'3'] -> COUNTRY = 'Unite...  100.0%     1,459       0
  5    EMPLOYER_ID [startswith:'1'] -> ACTIVE =...  100.0%       734       0
  6    PHONE [startswith:'2'] -> COUNTRY = 'Uni...  100.0%       381       0
  7    NAME [startswith:'C'] -> COUNTRY = 'Unit...  100.0%       345       0
  8    CITY [startswith:'N'] -> COUNTRY = 'Unit...  100.0%       316       0
  9    NAME [startswith:'S'] -> ACTIVE = 'Y'        100.0%       312       0
  10   NAME [startswith:'S'] -> COUNTRY = 'Unit...  100.0%       312       0
========================================================================

### Pipeline sur t1.csv (employés Montgomery, FD exacte)

On force `epsilon = 0.0` pour rechercher des **FDs exactes** uniquement.

In [15]:
pfds_t1 = discover(
    t1[["Department", "Department Name", "Division", "Assignment Category"]],
    epsilon=0.0, min_support=5, k_max=3, verbose=True
)
print_results(pfds_t1, top_n=8)

[1/4] Extraction des patterns  (k_max=3, min_support=5)...

    4 colonnes analysées, 671 patterns extraits

[2/4] Génération des candidats PFDs...

    1,863 candidats générés

[3/4] Validation (epsilon=0.0)...

    943 PFDs valides (sur 1,863 candidats testés)

[4/4] Généralisation des règles...
    455 règles conservées (41 généralisées, 488 élagées/fusionnées)

  Temps total : 4.44s

========================================================================
  #    Règle PFD                                      Conf   Support    Viol
========================================================================
  1    Department [startswith:'PO'] -> Departme...  100.0%     1,835       0 *
  2    Department [startswith:'HH'] -> Departme...  100.0%     1,512       0 *
  3    Department [startswith:'F'] -> Assignmen...  100.0%     1,392       0
  4    Department [startswith:'FR'] -> Departme...  100.0%     1,281       0 *
  5    Department Name [startswith:'F'] -> Assi...  100.0%     1,281       0
  6    Department Name [startswith:'F'] -> Depa...  100.0%     1,281       0 *
  7    Department [startswith:'DO'] -> Departme...  100.0%     1,199       0 *
  8    Division [startswith:'St'] -> Assignment...  100.0%       937       0
========================================================================
  * règle généralisée depuis plusieurs règles spécifiques

### Pipeline sur t3.csv (licences alcool Maryland)

In [16]:
pfds_t3 = discover(
    t3,
    epsilon=0.1, min_support=20, k_max=4, verbose=True
)
print_results(pfds_t3, top_n=8)

[1/4] Extraction des patterns  (k_max=4, min_support=20)...
    9 colonnes analysées, 222 patterns extraits

[2/4] Génération des candidats PFDs...

    1,723 candidats générés

[3/4] Validation (epsilon=0.1)...

    285 PFDs valides (sur 1,723 candidats testés)

[4/4] Généralisation des règles...
    108 règles conservées (8 généralisées, 177 élagées/fusionnées)

  Temps total : 2.59s

========================================================================
  #    Règle PFD                                      Conf   Support    Viol
========================================================================
  1    Zip [startswith:'2'] -> State = 'MD'         100.0%     1,076       0 *
  2    Channel Type [startswith:'O'] -> State =...  100.0%     1,075       0 *
  3    Licensee Number [startswith:'B'] -> Stat...  100.0%       625       0
  4    Location [startswith:'1'] -> State = 'MD'    100.0%       401       0
  5    Street [startswith:'1'] -> State = 'MD'      100.0%       401       0
  6    City [startswith:'S'] -> State = 'MD'        100.0%       272       0
  7    City [startswith:'G'] -> State = 'MD'        100.0%       231       0
  8    City [startswith:'R'] -> State = 'MD'        100.0%       208       0
========================================================================
  * règle généralisée depuis plusieurs règles spécifiques

---
## Discussion des résultats

### Statistiques globales

In [17]:
import pandas as pd

stats = pd.DataFrame([
    {"Dataset": "t1.csv", "Lignes": len(t1), "Colonnes": len(t1.columns),
     "PFDs découvertes": len(pfds_t1),
     "Conf. moyenne": f"{sum(r['confidence'] for r in pfds_t1)/max(len(pfds_t1),1):.1%}"},
    {"Dataset": "t2.csv", "Lignes": len(t2), "Colonnes": len(t2.columns),
     "PFDs découvertes": len(pfds_t2),
     "Conf. moyenne": f"{sum(r['confidence'] for r in pfds_t2)/max(len(pfds_t2),1):.1%}"},
    {"Dataset": "t3.csv", "Lignes": len(t3), "Colonnes": len(t3.columns),
     "PFDs découvertes": len(pfds_t3),
     "Conf. moyenne": f"{sum(r['confidence'] for r in pfds_t3)/max(len(pfds_t3),1):.1%}"},
])
stats

  Dataset  Lignes  Colonnes  PFDs découvertes Conf. moyenne
0  t1.csv    9101         9               455        100.0%
1  t2.csv    3502        13               324         97.6%
2  t3.csv    1077         9               108         98.7%

### Cas intéressants observés

**1. Détection d'incohérences de casse (t2.csv)**
La PFD `ZIP sw '606' → CITY = 'Chicago'` a 37 violations, toutes dues à
`'chicago'` en minuscules au lieu de `'Chicago'`. Ce sont des **erreurs de saisie**
détectables grâce à la PFD.

**2. Généralisation automatique (t3.csv)**
Le pipeline a découvert que `Licensee Number sw 'B' → Channel Type = 'On Premise'`
tient avec 94% de confiance. La lettre initiale `'B'` suffit ! C'est plus fort
que la PFD candidate du cours (`'BBW' → 'On Premise'`).

**3. Limites des approches purement syntaxiques (t2.csv)**
Les règles `ZIP sw '6' → COUNTRY = 'United States'`, `PHONE sw '3' → COUNTRY = '...'`,
etc. apparaissent en tête de classement avec 100% de confiance — mais ce sont
des règles **triviales** car `COUNTRY` est quasi-constant dans le dataset.
C'est exactement la limitation pointée slide 20 : *« No semantic understanding,
many spurious dependencies »*. Le **Workflow B (Guided Search)** de la Tâche 2
devrait corriger cela en demandant au LLM d'écarter ces colonnes peu discriminantes.

---
## Conclusion

Le pipeline classique implémenté couvre les 4 étapes prescrites par le cours :

| Étape | Slides cours | Implémentation                            | Résultat |
|-------|--------------|-------------------------------------------|----------|
| 1     | 9-10         | `extract_all_patterns`                    | Préfixes + tokens filtrés par support |
| 2     | 12-13        | `generate_all_candidates`                 | Candidats `(col_X, pattern_X, col_Y, top_Y)` |
| 3     | 14           | `verifier_pfd`                            | Filtrage par confiance ≥ 1-ε |
| 4     | 15           | `generalize_rules` (fusion + élagage)     | Réduction de 70% à 80% du nombre de règles |

### Prochaines étapes (cf. backlog GitHub)

- **Tâche 2** — implémenter le **Workflow B (Guided Search)** où un LLM
  sélectionne les colonnes et patterns pertinents avant validation.
- **Tâche 3** — comparer quantitativement les deux approches (nombre de PFDs,
  confiance moyenne, temps, interprétabilité) en utilisant à la fois Claude
  et Mistral comme LLMs.